
CREATE PROCEDURE [adm].[spFindBranchID_CL] (@RecID UNIQUEIDENTIFIER, @BranchUID UNIQUEIDENTIFIER OUTPUT)
AS
BEGIN

SET NOCOUNT ON
DECLARE @PrevRecUID	UNIQUEIDENTIFIER
SELECT @BranchUID = CL.BranchUID, @PrevRecUID = CL.PrevRecUID FROM adm.ColumnsLog CL WHERE CL.RecUID = @RecID
IF @BranchUID IS NULL
    EXEC adm.spFindBranchID_CL @PrevRecUID, @BranchUID OUTPUT

END