

CREATE PROCEDURE [adm].[spFindBranchID_TL] (@RecID UNIQUEIDENTIFIER, @BranchUID UNIQUEIDENTIFIER OUTPUT)
AS
BEGIN

SET NOCOUNT ON
DECLARE @PrevRecUID	UNIQUEIDENTIFIER
SELECT @BranchUID = TL.BranchUID, @PrevRecUID = TL.PrevRecUID FROM adm.TablesLog TL WHERE TL.RecUID = @RecID
IF @BranchUID IS NULL
    EXEC adm.spFindBranchID_TL @PrevRecUID, @BranchUID OUTPUT

END